version: '3'
services:
  api:
    depends_on:
      - mysql
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    env_file:
      - ./docker/mysql/mysql.env
    tty: 
      true
  mysql:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    env_file:
      - ./docker/mysql/mysql.env
    ports: 
      - "3306:3306"
    tty: 
      true
    volumes:
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files #<- https://github.com/docker-library/mysql/issues/541
volumes:
  mysql-data:

